function [Time1, Room_Num1, Device_ID1, RSSI_Left1, RSSI_Right1, Num_People1] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME1, ROOM_NUM1, DEVICE_ID1, RSSI_LEFT1, RSSI_RIGHT1, NUM_PEOPLE1]
%  = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [TIME1, ROOM_NUM1, DEVICE_ID1, RSSI_LEFT1, RSSI_RIGHT1, NUM_PEOPLE1]
%  = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [Time1, Room_Num1, Device_ID1, RSSI_Left1, RSSI_Right1, Num_People1] = importfile("E:\Projects\MAFAT_RSSI\mafat_wifi_challenge_training_set_v1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Apr-2022 22:11:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time1", "Room_Num1", "Device_ID1", "RSSI_Left1", "RSSI_Right1", "Num_People1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time1 = tbl.Time1;
Room_Num1 = tbl.Room_Num1;
Device_ID1 = tbl.Device_ID1;
RSSI_Left1 = tbl.RSSI_Left1;
RSSI_Right1 = tbl.RSSI_Right1;
Num_People1 = tbl.Num_People1;
end